env:
  browser: true
  es2021: true
extends:
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
plugins:
  - "@typescript-eslint"
rules: { no-var: 2, no-return-await: 2, no-throw-literal: 2 }
